#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WORKDIR = `pwd`

CC = gcc
CXX = g++
AR = ar
LD = g++
WINDRES = windres

INC = 
CFLAGS = -Wall -fexceptions
RESINC = 
LIBDIR = 
LIB = 
LDFLAGS = 

INC_RELEASE_LINUX = $(INC)
CFLAGS_RELEASE_LINUX = $(CFLAGS) -O3 -O2 -O1 -O
RESINC_RELEASE_LINUX = $(RESINC)
RCFLAGS_RELEASE_LINUX = $(RCFLAGS)
LIBDIR_RELEASE_LINUX = $(LIBDIR)
LIB_RELEASE_LINUX = $(LIB)-lGL -lSDL -lGLU -lopenal -lalut
LDFLAGS_RELEASE_LINUX = $(LDFLAGS) -s
OBJDIR_RELEASE_LINUX = .objs
DEP_RELEASE_LINUX = 
OUT_RELEASE_LINUX = offroad

OBJ_RELEASE_LINUX = $(OBJDIR_RELEASE_LINUX)/mrizka.o $(OBJDIR_RELEASE_LINUX)/offroad.o $(OBJDIR_RELEASE_LINUX)/objekty.o $(OBJDIR_RELEASE_LINUX)/objekt.o $(OBJDIR_RELEASE_LINUX)/obal.o $(OBJDIR_RELEASE_LINUX)/matika.o $(OBJDIR_RELEASE_LINUX)/loaddata.o $(OBJDIR_RELEASE_LINUX)/koule.o $(OBJDIR_RELEASE_LINUX)/wheel.o $(OBJDIR_RELEASE_LINUX)/vstup.o $(OBJDIR_RELEASE_LINUX)/tgaload.o $(OBJDIR_RELEASE_LINUX)/teren.o $(OBJDIR_RELEASE_LINUX)/konzole.o $(OBJDIR_RELEASE_LINUX)/suspension.o $(OBJDIR_RELEASE_LINUX)/struktury.o $(OBJDIR_RELEASE_LINUX)/soucastky.o $(OBJDIR_RELEASE_LINUX)/pruziny.o $(OBJDIR_RELEASE_LINUX)/Antirollbar.o $(OBJDIR_RELEASE_LINUX)/chodec.o $(OBJDIR_RELEASE_LINUX)/auto.o $(OBJDIR_RELEASE_LINUX)/Pacejka.o $(OBJDIR_RELEASE_LINUX)/AudioSystem.o $(OBJDIR_RELEASE_LINUX)/3Dmath/plane3d.o $(OBJDIR_RELEASE_LINUX)/3Dmath/Vec3D.o $(OBJDIR_RELEASE_LINUX)/3Dmath/Quat3D.o $(OBJDIR_RELEASE_LINUX)/kodovani.o $(OBJDIR_RELEASE_LINUX)/kamera.o $(OBJDIR_RELEASE_LINUX)/hud.o $(OBJDIR_RELEASE_LINUX)/glsl.o $(OBJDIR_RELEASE_LINUX)/3Dmath/Mat3D.o $(OBJDIR_RELEASE_LINUX)/glm.o $(OBJDIR_RELEASE_LINUX)/frustum.o

all: release_linux

clean: clean_release_linux

before_release_linux: 
	test -d $(OBJDIR_RELEASE_LINUX) || mkdir -p $(OBJDIR_RELEASE_LINUX)
	test -d $(OBJDIR_RELEASE_LINUX)/3Dmath || mkdir -p $(OBJDIR_RELEASE_LINUX)/3Dmath

after_release_linux: 

release_linux: before_release_linux out_release_linux after_release_linux

out_release_linux: before_release_linux $(OBJ_RELEASE_LINUX) $(DEP_RELEASE_LINUX)
	$(LD) $(LIBDIR_RELEASE_LINUX) -o $(OUT_RELEASE_LINUX) $(OBJ_RELEASE_LINUX)  $(LDFLAGS_RELEASE_LINUX) $(LIB_RELEASE_LINUX)

$(OBJDIR_RELEASE_LINUX)/mrizka.o: mrizka.cpp
	$(CXX) $(CFLAGS_RELEASE_LINUX) $(INC_RELEASE_LINUX) -c mrizka.cpp -o $(OBJDIR_RELEASE_LINUX)/mrizka.o

$(OBJDIR_RELEASE_LINUX)/offroad.o: offroad.cpp
	$(CXX) $(CFLAGS_RELEASE_LINUX) $(INC_RELEASE_LINUX) -c offroad.cpp -o $(OBJDIR_RELEASE_LINUX)/offroad.o

$(OBJDIR_RELEASE_LINUX)/objekty.o: objekty.cpp
	$(CXX) $(CFLAGS_RELEASE_LINUX) $(INC_RELEASE_LINUX) -c objekty.cpp -o $(OBJDIR_RELEASE_LINUX)/objekty.o

$(OBJDIR_RELEASE_LINUX)/objekt.o: objekt.cpp
	$(CXX) $(CFLAGS_RELEASE_LINUX) $(INC_RELEASE_LINUX) -c objekt.cpp -o $(OBJDIR_RELEASE_LINUX)/objekt.o

$(OBJDIR_RELEASE_LINUX)/obal.o: obal.cpp
	$(CXX) $(CFLAGS_RELEASE_LINUX) $(INC_RELEASE_LINUX) -c obal.cpp -o $(OBJDIR_RELEASE_LINUX)/obal.o

$(OBJDIR_RELEASE_LINUX)/matika.o: matika.cpp
	$(CXX) $(CFLAGS_RELEASE_LINUX) $(INC_RELEASE_LINUX) -c matika.cpp -o $(OBJDIR_RELEASE_LINUX)/matika.o

$(OBJDIR_RELEASE_LINUX)/loaddata.o: loaddata.cpp
	$(CXX) $(CFLAGS_RELEASE_LINUX) $(INC_RELEASE_LINUX) -c loaddata.cpp -o $(OBJDIR_RELEASE_LINUX)/loaddata.o

$(OBJDIR_RELEASE_LINUX)/koule.o: koule.cpp
	$(CXX) $(CFLAGS_RELEASE_LINUX) $(INC_RELEASE_LINUX) -c koule.cpp -o $(OBJDIR_RELEASE_LINUX)/koule.o

$(OBJDIR_RELEASE_LINUX)/wheel.o: wheel.cpp
	$(CXX) $(CFLAGS_RELEASE_LINUX) $(INC_RELEASE_LINUX) -c wheel.cpp -o $(OBJDIR_RELEASE_LINUX)/wheel.o

$(OBJDIR_RELEASE_LINUX)/vstup.o: vstup.cpp
	$(CXX) $(CFLAGS_RELEASE_LINUX) $(INC_RELEASE_LINUX) -c vstup.cpp -o $(OBJDIR_RELEASE_LINUX)/vstup.o

$(OBJDIR_RELEASE_LINUX)/tgaload.o: tgaload.cpp
	$(CXX) $(CFLAGS_RELEASE_LINUX) $(INC_RELEASE_LINUX) -c tgaload.cpp -o $(OBJDIR_RELEASE_LINUX)/tgaload.o

$(OBJDIR_RELEASE_LINUX)/teren.o: teren.cpp
	$(CXX) $(CFLAGS_RELEASE_LINUX) $(INC_RELEASE_LINUX) -c teren.cpp -o $(OBJDIR_RELEASE_LINUX)/teren.o

$(OBJDIR_RELEASE_LINUX)/konzole.o: konzole.cpp
	$(CXX) $(CFLAGS_RELEASE_LINUX) $(INC_RELEASE_LINUX) -c konzole.cpp -o $(OBJDIR_RELEASE_LINUX)/konzole.o

$(OBJDIR_RELEASE_LINUX)/suspension.o: suspension.cpp
	$(CXX) $(CFLAGS_RELEASE_LINUX) $(INC_RELEASE_LINUX) -c suspension.cpp -o $(OBJDIR_RELEASE_LINUX)/suspension.o

$(OBJDIR_RELEASE_LINUX)/struktury.o: struktury.cpp
	$(CXX) $(CFLAGS_RELEASE_LINUX) $(INC_RELEASE_LINUX) -c struktury.cpp -o $(OBJDIR_RELEASE_LINUX)/struktury.o

$(OBJDIR_RELEASE_LINUX)/soucastky.o: soucastky.cpp
	$(CXX) $(CFLAGS_RELEASE_LINUX) $(INC_RELEASE_LINUX) -c soucastky.cpp -o $(OBJDIR_RELEASE_LINUX)/soucastky.o

$(OBJDIR_RELEASE_LINUX)/pruziny.o: pruziny.cpp
	$(CXX) $(CFLAGS_RELEASE_LINUX) $(INC_RELEASE_LINUX) -c pruziny.cpp -o $(OBJDIR_RELEASE_LINUX)/pruziny.o

$(OBJDIR_RELEASE_LINUX)/Antirollbar.o: Antirollbar.cpp
	$(CXX) $(CFLAGS_RELEASE_LINUX) $(INC_RELEASE_LINUX) -c Antirollbar.cpp -o $(OBJDIR_RELEASE_LINUX)/Antirollbar.o

$(OBJDIR_RELEASE_LINUX)/chodec.o: chodec.cpp
	$(CXX) $(CFLAGS_RELEASE_LINUX) $(INC_RELEASE_LINUX) -c chodec.cpp -o $(OBJDIR_RELEASE_LINUX)/chodec.o

$(OBJDIR_RELEASE_LINUX)/auto.o: auto.cpp
	$(CXX) $(CFLAGS_RELEASE_LINUX) $(INC_RELEASE_LINUX) -c auto.cpp -o $(OBJDIR_RELEASE_LINUX)/auto.o

$(OBJDIR_RELEASE_LINUX)/Pacejka.o: Pacejka.cpp
	$(CXX) $(CFLAGS_RELEASE_LINUX) $(INC_RELEASE_LINUX) -c Pacejka.cpp -o $(OBJDIR_RELEASE_LINUX)/Pacejka.o

$(OBJDIR_RELEASE_LINUX)/AudioSystem.o: AudioSystem.cpp
	$(CXX) $(CFLAGS_RELEASE_LINUX) $(INC_RELEASE_LINUX) -c AudioSystem.cpp -o $(OBJDIR_RELEASE_LINUX)/AudioSystem.o

$(OBJDIR_RELEASE_LINUX)/3Dmath/plane3d.o: 3Dmath/plane3d.cpp
	$(CXX) $(CFLAGS_RELEASE_LINUX) $(INC_RELEASE_LINUX) -c 3Dmath/plane3d.cpp -o $(OBJDIR_RELEASE_LINUX)/3Dmath/plane3d.o

$(OBJDIR_RELEASE_LINUX)/3Dmath/Vec3D.o: 3Dmath/Vec3D.cpp
	$(CXX) $(CFLAGS_RELEASE_LINUX) $(INC_RELEASE_LINUX) -c 3Dmath/Vec3D.cpp -o $(OBJDIR_RELEASE_LINUX)/3Dmath/Vec3D.o

$(OBJDIR_RELEASE_LINUX)/3Dmath/Quat3D.o: 3Dmath/Quat3D.cpp
	$(CXX) $(CFLAGS_RELEASE_LINUX) $(INC_RELEASE_LINUX) -c 3Dmath/Quat3D.cpp -o $(OBJDIR_RELEASE_LINUX)/3Dmath/Quat3D.o

$(OBJDIR_RELEASE_LINUX)/kodovani.o: kodovani.cpp
	$(CXX) $(CFLAGS_RELEASE_LINUX) $(INC_RELEASE_LINUX) -c kodovani.cpp -o $(OBJDIR_RELEASE_LINUX)/kodovani.o

$(OBJDIR_RELEASE_LINUX)/kamera.o: kamera.cpp
	$(CXX) $(CFLAGS_RELEASE_LINUX) $(INC_RELEASE_LINUX) -c kamera.cpp -o $(OBJDIR_RELEASE_LINUX)/kamera.o

$(OBJDIR_RELEASE_LINUX)/hud.o: hud.cpp
	$(CXX) $(CFLAGS_RELEASE_LINUX) $(INC_RELEASE_LINUX) -c hud.cpp -o $(OBJDIR_RELEASE_LINUX)/hud.o

$(OBJDIR_RELEASE_LINUX)/glsl.o: glsl.cpp
	$(CXX) $(CFLAGS_RELEASE_LINUX) $(INC_RELEASE_LINUX) -c glsl.cpp -o $(OBJDIR_RELEASE_LINUX)/glsl.o

$(OBJDIR_RELEASE_LINUX)/3Dmath/Mat3D.o: 3Dmath/Mat3D.cpp
	$(CXX) $(CFLAGS_RELEASE_LINUX) $(INC_RELEASE_LINUX) -c 3Dmath/Mat3D.cpp -o $(OBJDIR_RELEASE_LINUX)/3Dmath/Mat3D.o

$(OBJDIR_RELEASE_LINUX)/glm.o: glm.cpp
	$(CXX) $(CFLAGS_RELEASE_LINUX) $(INC_RELEASE_LINUX) -c glm.cpp -o $(OBJDIR_RELEASE_LINUX)/glm.o

$(OBJDIR_RELEASE_LINUX)/frustum.o: frustum.cpp
	$(CXX) $(CFLAGS_RELEASE_LINUX) $(INC_RELEASE_LINUX) -c frustum.cpp -o $(OBJDIR_RELEASE_LINUX)/frustum.o

clean_release_linux: 
	rm -f $(OBJ_RELEASE_LINUX) $(OUT_RELEASE_LINUX)
	rm -rf $(OBJDIR_RELEASE_LINUX)
	rm -rf $(OBJDIR_RELEASE_LINUX)/3Dmath

.PHONY: before_release_linux after_release_linux clean_release_linux

